
gem 'devise', github: 'heartcombo/devise', branch: 'ca-omniauth-2'
gem 'email_validator'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-google-oauth2'
gem 'omniauth-rails_csrf_protection'
gem 'rolify'
